### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by ranierivalenca** [gmatheus66/reqon#116]
## Sprint 7
- [ ] Encaminhamento de requerimentos para outros setores

## Sprint 8
- [x] Separar os requerimentos dos funcionários por setor (um funcionário da CRADT só vê os requerimentos que estão na CRADT)

## Sprint 10
- [ ] Ajustes no processo de interação no detalhe dos requerimentos com filhos e encaminhamentos
- [ ] Expandir e colapsar as informações dos detalhes dos requerimentos
- [x] Paginação dos requerimentos ( aluno e funcionário)
