### ISSUE TITLE
Sprint 13

### ISSUE THREAD

**Issue by lilialnas** [gmatheus66/reqon#147]
- [x] Ajustes no fluxo do requerimento
- [x] Implementação do Docker
- [x] Ajustes no frontend do requerimento
- [x] Melhoria do breadcrumbs do requerimento
- [x] Ajustes no footer e header ( remover informações e funcionalidades repetidas)
