### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by lilialnas** [gmatheus66/reqon#38]
- [ ] Migração do banco de dados 
- [ ] Estudar mecanismo de seed do Laravel 
- [ ] Popular tabelas (todas exceto requerimento e anexo) com o mecanismo de seed 
- [ ] Login de estudante levando para tela com escolha de curso para o qual quer abrir requerimento
