### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by lilialnas** [gmatheus66/reqon#39]
## Sprint 3
- [x] Migração do banco de dados
- [x] Popular tabelas (todas exceto requerimento e anexo) com o mecanismo de seed
- [ ] Login de estudante levando para tela com escolha de curso para o qual quer abrir requerimento

## Sprint 4
- [ ] Cadastro de requerimento por estudante 
- [ ] Login de funcionário com listagem de requerimentos direcionados à ele ou a algum dos setores que faz parte
