### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by ranierivalenca** [gmatheus66/reqon#51]
## Sprint 3
- [x]  Login de estudante
- [ ] Tela de escolha de curso para abrir requerimento

## Sprint 4
- [x] Cadastro de requerimento por estudante
- [ ] Login de funcionário com listagem de requerimentos direcionados à ele ou a algum dos setores que faz parte
