### ISSUE TITLE
Sprint 6

### ISSUE THREAD

**Issue by ranierivalenca** [gmatheus66/reqon#66]
## Sprint 3
- [x] Tela de escolha de curso para abrir requerimento (para estudante)

## Sprint 4
- [ ] Login de funcionário 
- [ ] Listagem de requerimentos direcionados ao funcionário ou a algum dos setores que faz parte

## Sprint 6
- [ ] Listagem de requerimentos abertos pelo estudante
- [ ] Unificação dos logins de estudante e funcionário
- [ ] Terminar front-end da home do estudante
- [ ] Feedbacks de cadastro de requerimento
