### ISSUE TITLE
Sprint 7

### ISSUE THREAD

**Issue by ranierivalenca** [gmatheus66/reqon#82]
## Sprint 4
- [x] Login de funcionário 
- [x] Listagem de requerimentos direcionados ao funcionário ou a algum dos setores que faz parte

## Sprint 6
- [x] Listagem de requerimentos abertos pelo estudante
- [x] Unificação dos logins de estudante e funcionário
- [ ] Terminar front-end da home do estudante
- [x] Feedbacks de cadastro de requerimento

## Sprint 7
- [ ] Encaminhamento de requerimentos para outros setores
