### ISSUE TITLE
Sprint 8

### ISSUE THREAD

**Issue by ranierivalenca** [gmatheus66/reqon#86]
## Sprint 6
- [x] Terminar front-end da home do estudante\

## Sprint 7
- [ ] Encaminhamento de requerimentos para outros setores

## Sprint 8
- [ ] Separar os requerimentos dos funcionários por setor (um funcionário da CRADT só vê os requerimentos que estão na CRADT)
- [x] Ajuste na ordenação dos requerimentos (mais novos primeiro (para estudantes e para funcionários))
- [x] Melhorar o front-end (o footer tá ficando por cima dos elementos ¬¬)
- [x] Detalhes do Requerimento (apenas do inicial) (tela preparada para o fluxo completo (estilo reddit))
